# -- Values to pass to [the upstream cni chart](https://github.com/istio/istio/blob/master/manifests/charts/istio-cni/values.yaml)
# @default -- Upstream chart values
upstream:
  ambient:
    enabled: false
  global:
    hub: registry1.dso.mil/ironbank/opensource/istio
    tag: 1.28.2
    imagePullPolicy: "Always"
    imagePullSecrets:
      - private-registry